/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.Random;
/**
 *
 * @author eljam3239
 */
public class additionpage extends javax.swing.JFrame {
        
    
    Random rand = new Random();
    //generate the random numbers that change with each use    
    int num1 = rand.nextInt(50)+15;
    int num2 = rand.nextInt(50)+15;
    int num3 = rand.nextInt(50)+15;
    int num4 = rand.nextInt(50)+15;
    int num5 = rand.nextInt(50)+15;
    int num6 = rand.nextInt(50)+15;
    
    //determines what the correct answers are
    int mathans1 = num1+num2;
    int mathans2 = num3+num4;
    int mathans3 = num5+num6;
       
    /**
     * Creates new form additionpage
     */
    public additionpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        additionbackground = new javax.swing.JPanel();
        Additiontitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        additionlesson = new javax.swing.JTextArea();
        addq1 = new javax.swing.JLabel();
        addq2 = new javax.swing.JLabel();
        addq3 = new javax.swing.JLabel();
        addq1ans = new javax.swing.JTextField();
        addq2ans = new javax.swing.JTextField();
        addq3ans = new javax.swing.JTextField();
        addhome = new javax.swing.JButton();
        addansout = new javax.swing.JLabel();
        addsenter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        additionbackground.setBackground(new java.awt.Color(15, 22, 38));

        Additiontitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Additiontitle.setForeground(new java.awt.Color(255, 255, 255));
        Additiontitle.setText("Addition with Three Digits");

        additionlesson.setBackground(new java.awt.Color(15, 22, 38));
        additionlesson.setColumns(20);
        additionlesson.setForeground(new java.awt.Color(255, 255, 255));
        additionlesson.setRows(5);
        additionlesson.setText("Addition with single digits is easy. We all know\nthat 3+4 is 7 or that 6+9 is 15. When we add two\nterms with double digits, things can become more\ncomplicated. This first trick is simple: try \nbreaking one of two terms into its multiples of\n10. Here's what I mean:\n\nInstead of trying to compute 43+18 all at once,\ntry splitting 18 to 10+8. You could now tackle \nthe question as (43+10)+8 which now more clearly\nequals 61. *** pro tip: try saying the problem\nin your head, like this: \"forty three plus eight\nteen is equal to forty three plus ten is fifty\nthree plus eight is sixty-one\".\n\nNow you try!\n");
        jScrollPane1.setViewportView(additionlesson);

        addq1.setForeground(new java.awt.Color(255, 255, 255));

        addq2.setForeground(new java.awt.Color(255, 255, 255));

        addq3.setForeground(new java.awt.Color(255, 255, 255));
        addq3.setText("jLabel1");

        addhome.setForeground(new java.awt.Color(15, 22, 38));
        addhome.setText("<--Home");
        addhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addhomeActionPerformed(evt);
            }
        });

        addansout.setForeground(new java.awt.Color(255, 255, 255));

        addsenter.setBackground(new java.awt.Color(255, 255, 255));
        addsenter.setForeground(new java.awt.Color(15, 22, 38));
        addsenter.setText("Enter");
        addsenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsenterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout additionbackgroundLayout = new javax.swing.GroupLayout(additionbackground);
        additionbackground.setLayout(additionbackgroundLayout);
        additionbackgroundLayout.setHorizontalGroup(
            additionbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(additionbackgroundLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(addhome)
                .addGap(18, 18, 18)
                .addComponent(Additiontitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, additionbackgroundLayout.createSequentialGroup()
                .addGap(0, 91, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, additionbackgroundLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(additionbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addq1ans, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addq1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(additionbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, additionbackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                        .addComponent(addansout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(additionbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addq3)
                            .addComponent(addq3ans, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, additionbackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(additionbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addsenter)
                            .addComponent(addq2ans, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addq2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(197, 197, 197))))
        );
        additionbackgroundLayout.setVerticalGroup(
            additionbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(additionbackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(additionbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addhome)
                    .addComponent(Additiontitle))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(additionbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addq1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(additionbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addq3)
                        .addComponent(addq2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(additionbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addq1ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addq2ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addq3ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addsenter)
                .addGap(29, 29, 29)
                .addComponent(addansout)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(additionbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(additionbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    //allows the user to travel between panels
    private void addhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addhomeActionPerformed
        new titlepage().setVisible(true);
        this.setVisible(false);
        //
    }//GEN-LAST:event_addhomeActionPerformed
    
    
    
    private void addsenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsenterActionPerformed
        int numCorrect =0;
        String feedback = "";
        
        
        //receive the user's inputted answers
        int ans1 =Integer.parseInt(addq1ans.getText());
        int ans2 =Integer.parseInt(addq2ans.getText());
        int ans3 =Integer.parseInt(addq3ans.getText());
        
        if (ans1 == mathans1){//accumulator that increase depending on user's success
            numCorrect++;
        }
        
        if (ans2 == mathans2){
            numCorrect++;
        }
        
        if (ans3 == mathans3){
            numCorrect++;
        }
        System.out.print(numCorrect);
        switch(numCorrect){//determines how well the user did
            case 0: feedback = "You scored 0%. Try harder."; break;
            case 1: feedback = "You scored 33%. You can do better!."; break;
            case 2: feedback = "You scored 66%. That's great!."; break;
            case 3: feedback = "You scored 100%, what are you, a genius?"; break;    
        }
        addansout.setText(feedback);//tells the user how well they performed
        
    }//GEN-LAST:event_addsenterActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        addq1.setText(num1+" + "+num2);//shows the user their randomly generated questions
        addq2.setText(num3+" + "+num4);
        addq3.setText(num5+" + "+num6);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(additionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(additionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(additionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(additionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new additionpage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Additiontitle;
    private javax.swing.JLabel addansout;
    private javax.swing.JButton addhome;
    private javax.swing.JPanel additionbackground;
    private javax.swing.JTextArea additionlesson;
    private javax.swing.JLabel addq1;
    private javax.swing.JTextField addq1ans;
    private javax.swing.JLabel addq2;
    private javax.swing.JTextField addq2ans;
    private javax.swing.JLabel addq3;
    private javax.swing.JTextField addq3ans;
    private javax.swing.JButton addsenter;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
