/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.Random;


/**
 *
 * @author eljam3239
 */
public class subtractionpage extends javax.swing.JFrame {

    Random rand = new Random();
    //generates the random numbers to be subracted from one another
    int num1 = rand.nextInt(30)+10;
    int num2 = rand.nextInt(80)+20;
    int num3 = rand.nextInt(30)+10;
    int num4 = rand.nextInt(80)+20;
    int num5 = rand.nextInt(30)+10;
    int num6 = rand.nextInt(80)+20;
    int num7 = rand.nextInt(300)+100;
    int num8 = rand.nextInt(900)+100;
    //determines the correct answers
    int ans1 = num2-num1;
    int ans2 = num4-num3;
    int ans3 = num6-num5;
    int ans4 = num8-num7;
    
    
    /**
     * Creates new form subtractionpage
     */
    public subtractionpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subpanelbackground = new javax.swing.JPanel();
        subhomebutton = new javax.swing.JButton();
        subtitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lessontext = new javax.swing.JTextArea();
        subq1 = new javax.swing.JLabel();
        subq2 = new javax.swing.JLabel();
        subq3 = new javax.swing.JLabel();
        subuans1 = new javax.swing.JTextField();
        subuans2 = new javax.swing.JTextField();
        subuans3 = new javax.swing.JTextField();
        subbonusq = new javax.swing.JLabel();
        subbonusuans = new javax.swing.JTextField();
        subfeedback = new javax.swing.JLabel();
        subenter = new javax.swing.JButton();
        subq4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        subpanelbackground.setBackground(new java.awt.Color(38, 15, 18));

        subhomebutton.setText("<--Home");
        subhomebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subhomebuttonActionPerformed(evt);
            }
        });

        subtitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        subtitle.setForeground(new java.awt.Color(255, 255, 255));
        subtitle.setText("Mental Subtraction");

        lessontext.setColumns(20);
        lessontext.setForeground(new java.awt.Color(38, 15, 18));
        lessontext.setRows(5);
        lessontext.setText("There are two techniques to do any mental subtraction\nprobelm. \n\n1. Like the addition trick, subract each digit as a multiple\nof ten. Like this: 37-16=(37-10)-6 = 21\n\n2. This trick involves subtracting the closest multiple of 10\nthen adding however much you wen tover by like this:\n37-16=(37-20)+4.\n\nNow you try a couple! See if you can use the same technique\nbut with a three digit subtraction.\n\n");
        jScrollPane1.setViewportView(lessontext);

        subq1.setForeground(new java.awt.Color(255, 255, 255));
        subq1.setText("jLabel1");

        subq2.setForeground(new java.awt.Color(255, 255, 255));
        subq2.setText("jLabel1");

        subq3.setForeground(new java.awt.Color(255, 255, 255));
        subq3.setText("jLabel1");

        subbonusq.setForeground(new java.awt.Color(255, 255, 255));
        subbonusq.setText("***Bonus***");

        subenter.setText("Enter");
        subenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subenterActionPerformed(evt);
            }
        });

        subq4.setForeground(new java.awt.Color(255, 255, 255));
        subq4.setText("jLabel1");

        javax.swing.GroupLayout subpanelbackgroundLayout = new javax.swing.GroupLayout(subpanelbackground);
        subpanelbackground.setLayout(subpanelbackgroundLayout);
        subpanelbackgroundLayout.setHorizontalGroup(
            subpanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subpanelbackgroundLayout.createSequentialGroup()
                .addGroup(subpanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subpanelbackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subhomebutton))
                    .addGroup(subpanelbackgroundLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(subq1)
                        .addGap(87, 87, 87)
                        .addComponent(subq2)
                        .addGap(109, 109, 109)
                        .addGroup(subpanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subuans3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subq3)))
                    .addGroup(subpanelbackgroundLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(subpanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subfeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(subpanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(subpanelbackgroundLayout.createSequentialGroup()
                                    .addGap(132, 132, 132)
                                    .addGroup(subpanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(subbonusuans, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(subpanelbackgroundLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(subenter))))
                                .addGroup(subpanelbackgroundLayout.createSequentialGroup()
                                    .addGroup(subpanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(subpanelbackgroundLayout.createSequentialGroup()
                                            .addGap(13, 13, 13)
                                            .addComponent(subuans1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(subpanelbackgroundLayout.createSequentialGroup()
                                            .addGap(51, 51, 51)
                                            .addComponent(subbonusq)))
                                    .addGap(20, 20, 20)
                                    .addGroup(subpanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(subq4)
                                        .addComponent(subuans2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(subpanelbackgroundLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(subtitle)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        subpanelbackgroundLayout.setVerticalGroup(
            subpanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subpanelbackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subhomebutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subpanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subq1)
                    .addComponent(subq2)
                    .addComponent(subq3))
                .addGap(26, 26, 26)
                .addGroup(subpanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subuans1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subuans2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subuans3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(subpanelbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subbonusq)
                    .addComponent(subq4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subbonusuans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subenter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(subfeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subpanelbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(subpanelbackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //allows users to navigate through pages
    private void subhomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subhomebuttonActionPerformed
        new titlepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_subhomebuttonActionPerformed

    private void subenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subenterActionPerformed
        String feedback = "";
        String bonus="";
        int numCorrect = 0;
        //receives what the user inputs as their answers to be compared with the correct ones
        int uans1= Integer.parseInt(subuans1.getText());
        int uans2= Integer.parseInt(subuans2.getText());
        int uans3= Integer.parseInt(subuans3.getText());
        int uans4= Integer.parseInt(subbonusuans.getText());
        //determines how many answers the user got correct
        if (uans1 == ans1){
            numCorrect++;
        }
        if (uans2 == ans2){
            numCorrect++;
        }
        if (uans3 == ans3){
            numCorrect++;
        }
        if (uans4 == ans4){
            bonus= " Incredible, you got the bonus!";
        }
        //determines how well the user did base on the number of correct answers
        switch(numCorrect){
            case 0: feedback = "You scored 0%, try harder."; break;
            case 1: feedback = "You scored 33%, I know you can do better!"; break;
            case 2: feedback = "You score 66%. Great!"; break;
            case 3: feedback = "You scored 100%, nice one genius!"; break;    
        }
        //displays to the user how well they did
        subfeedback.setText(feedback+bonus);
        
    }//GEN-LAST:event_subenterActionPerformed
    //displays the randomly generated questions
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        subq1.setText(num2+" - "+num1);
        subq2.setText(num4+" - "+num3);
        subq3.setText(num6+" - "+num5);
        subq4.setText(num8+" - "+num7);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subtractionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subtractionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subtractionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subtractionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subtractionpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lessontext;
    private javax.swing.JLabel subbonusq;
    private javax.swing.JTextField subbonusuans;
    private javax.swing.JButton subenter;
    private javax.swing.JLabel subfeedback;
    private javax.swing.JButton subhomebutton;
    private javax.swing.JPanel subpanelbackground;
    private javax.swing.JLabel subq1;
    private javax.swing.JLabel subq2;
    private javax.swing.JLabel subq3;
    private javax.swing.JLabel subq4;
    private javax.swing.JLabel subtitle;
    private javax.swing.JTextField subuans1;
    private javax.swing.JTextField subuans2;
    private javax.swing.JTextField subuans3;
    // End of variables declaration//GEN-END:variables
}
