/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eljam3239
 */
public class titlepage extends javax.swing.JFrame {

    /**
     * Creates new form titlepage
     */
    public titlepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        titlebackground = new javax.swing.JPanel();
        titlebanner = new javax.swing.JPanel();
        Additionlink = new javax.swing.JPanel();
        additionbuttonlink = new javax.swing.JButton();
        subtractionlink = new javax.swing.JPanel();
        subtractbuttonlink = new javax.swing.JButton();
        multiplylink = new javax.swing.JPanel();
        multiplicationbuttonlink = new javax.swing.JButton();
        dividelink = new javax.swing.JPanel();
        divisionbuttonlink = new javax.swing.JButton();
        greeting = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlebackground.setBackground(new java.awt.Color(15, 22, 36));

        titlebanner.setBackground(new java.awt.Color(245, 245, 245));

        Additionlink.setBackground(new java.awt.Color(15, 22, 38));

        additionbuttonlink.setText("+");
        additionbuttonlink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionbuttonlinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdditionlinkLayout = new javax.swing.GroupLayout(Additionlink);
        Additionlink.setLayout(AdditionlinkLayout);
        AdditionlinkLayout.setHorizontalGroup(
            AdditionlinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdditionlinkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(additionbuttonlink)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdditionlinkLayout.setVerticalGroup(
            AdditionlinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdditionlinkLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(additionbuttonlink)
                .addContainerGap())
        );

        subtractionlink.setBackground(new java.awt.Color(255, 83, 61));

        subtractbuttonlink.setText("-");
        subtractbuttonlink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractbuttonlinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subtractionlinkLayout = new javax.swing.GroupLayout(subtractionlink);
        subtractionlink.setLayout(subtractionlinkLayout);
        subtractionlinkLayout.setHorizontalGroup(
            subtractionlinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subtractionlinkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subtractbuttonlink)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subtractionlinkLayout.setVerticalGroup(
            subtractionlinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subtractionlinkLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(subtractbuttonlink)
                .addContainerGap())
        );

        multiplylink.setBackground(new java.awt.Color(171, 152, 122));

        multiplicationbuttonlink.setText("x");
        multiplicationbuttonlink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationbuttonlinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout multiplylinkLayout = new javax.swing.GroupLayout(multiplylink);
        multiplylink.setLayout(multiplylinkLayout);
        multiplylinkLayout.setHorizontalGroup(
            multiplylinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiplylinkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(multiplicationbuttonlink)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        multiplylinkLayout.setVerticalGroup(
            multiplylinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiplylinkLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(multiplicationbuttonlink)
                .addContainerGap())
        );

        dividelink.setBackground(new java.awt.Color(38, 15, 18));

        divisionbuttonlink.setText("÷");
        divisionbuttonlink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionbuttonlinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dividelinkLayout = new javax.swing.GroupLayout(dividelink);
        dividelink.setLayout(dividelinkLayout);
        dividelinkLayout.setHorizontalGroup(
            dividelinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dividelinkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(divisionbuttonlink)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dividelinkLayout.setVerticalGroup(
            dividelinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dividelinkLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(divisionbuttonlink)
                .addContainerGap())
        );

        javax.swing.GroupLayout titlebannerLayout = new javax.swing.GroupLayout(titlebanner);
        titlebanner.setLayout(titlebannerLayout);
        titlebannerLayout.setHorizontalGroup(
            titlebannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlebannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Additionlink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subtractionlink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(multiplylink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dividelink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        titlebannerLayout.setVerticalGroup(
            titlebannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlebannerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titlebannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Additionlink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(titlebannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dividelink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(titlebannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(multiplylink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subtractionlink, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        greeting.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        greeting.setForeground(new java.awt.Color(255, 255, 255));
        greeting.setText("Become a Mathemagician.");

        jTextArea1.setBackground(new java.awt.Color(15, 22, 38));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Welcome. In a few short lessons,\nyou will develop the ability to \nperform lightning-fast mental \ncalculations. Use these tricks to\nimpress your friends, ace a test\nor test your mental ability. \nClick on one of the above links \nto begin.\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout titlebackgroundLayout = new javax.swing.GroupLayout(titlebackground);
        titlebackground.setLayout(titlebackgroundLayout);
        titlebackgroundLayout.setHorizontalGroup(
            titlebackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlebanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(titlebackgroundLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(titlebackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(titlebackgroundLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(greeting)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlebackgroundLayout.setVerticalGroup(
            titlebackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlebackgroundLayout.createSequentialGroup()
                .addComponent(titlebanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(greeting)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlebackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlebackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//brings the user to the subtraction page
    private void subtractbuttonlinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractbuttonlinkActionPerformed
        new subtractionpage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_subtractbuttonlinkActionPerformed
//brings the user to the multiplicaton page
    private void multiplicationbuttonlinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationbuttonlinkActionPerformed
        new multiplypage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_multiplicationbuttonlinkActionPerformed
//brings the user to the addition page
    private void additionbuttonlinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionbuttonlinkActionPerformed
        new additionpage().setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_additionbuttonlinkActionPerformed
//brings the user to the division page
    private void divisionbuttonlinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionbuttonlinkActionPerformed
        new dividepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_divisionbuttonlinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(titlepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(titlepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(titlepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(titlepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new titlepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Additionlink;
    private javax.swing.JButton additionbuttonlink;
    private javax.swing.JPanel dividelink;
    private javax.swing.JButton divisionbuttonlink;
    private javax.swing.JLabel greeting;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton multiplicationbuttonlink;
    private javax.swing.JPanel multiplylink;
    private javax.swing.JButton subtractbuttonlink;
    private javax.swing.JPanel subtractionlink;
    private javax.swing.JPanel titlebackground;
    private javax.swing.JPanel titlebanner;
    // End of variables declaration//GEN-END:variables
}
